### ISSUE TITLE
[request] Add simple CSS for images

### ISSUE THREAD

**Issue by mesqueeb** [alexsasharegan/vue-transmit#10]
Hello,

I'd love if you could add simple CSS to get a single image uploader like so:

1. <img width="329" alt="2017-11-23 16 37 14" src="https://user-images.githubusercontent.com/3253920/33162383-ae1fa19c-d06c-11e7-9a32-ed193a076199.png">
2. <img width="322" alt="2017-11-23 16 37 28" src="https://user-images.githubusercontent.com/3253920/33162385-afe34df8-d06c-11e7-9af3-af348d21e36b.png">

**Comment by alexsasharegan** [comment]
This package is meant to support the uploading logic and leave styling up to each application. Unfortunately, adding custom/default styling is out of scope.

**Comment by alexsasharegan** [comment]
I'm reading these on my phone today, so if you were just asking for examples, I misunderstood. A few good example implementations would be a nice addition.
