### ISSUE TITLE
[doc clarification request]

### ISSUE THREAD

**Issue by mesqueeb** [alexsasharegan/vue-transmit#11]
In the options in the docs it says:

`maxFileSize | Number | 256`

I'd love you to add a little clarification to what 256 means: kb? mb? gb?

**Comment by alexsasharegan** [comment]
It's in Mib, the base 2 version of Mb (n << 20 || n * 1024 * 1024). There is a code comment, but I'll add notes in the docs as well.

I have been meaning to make the base configurable.

**Comment by alexsasharegan** [comment]
This is now specified in the [readme](https://github.com/alexsasharegan/vue-transmit/blob/master/README.md#props-vue-transmit).
