### ISSUE TITLE
Fetch transmitted events

### ISSUE THREAD

**Issue by sergeypoprovka** [alexsasharegan/vue-transmit#13]
Hey!
Trying to fetch 'upload-progress' event at the child component. And can't get how can I do that...:(

Trying to v-on:upload-progress inside parent component - and nothing happens...

Can you give me a hint, pls? Thanks!

**Comment by alexsasharegan** [comment]
Could you copy in some markup to show me what you're working with?

**Comment by sergeypoprovka** [comment]
Sure:

`<template>
    <div class="upload-form">
            <div class="upload-process" v-on:upload-progress="cl()">
                <div class="text-center" v-text="progress + '%'">
                </div>
                <div class="upload-process-bar">
                    <div class="upload-process-bar-inner" style="width:45%"></div>
                </div>
            </div>
            <div class="row video-upload-step-1" v-if="this.currentBlock == 1">
                <div class="col-md-8 col-md-offset-2">
                    <vue-transmit class="col-12"
                                  tag="section"
                                  v-bind="options"
                                  drop-zone-classes="bg-faded"
                                  v-on:sending="startUploadProcess()"
                                  ref="uploader">
                        <div class="d-flex align-items-center justify-content-center w-100"
                             style="border-radius: 1rem;">
                            <div class="text-center dz-message">
                            <img src="/img/video-movie-play.svg" />
                            <br><br>
                            <div>
                            <a href="#" class="btn btn-warning btn-block">Select file to upload</a>
                            </div>
                            <br><br>
                            <p>Or drag and drop film here</p>
                            </div>
                        </div>
                        
                        <template slot="files" slot-scope="props">
                            <div v-for="(file, i) in props.files" :key="file.id" :class="{'mt-5': i === 0}">
                                <div class="media">
                                    <img :src="file.dataUrl" class="img-fluid d-flex mr-3">
                                    <div class="media-body">
                                        <h3>{{ file.name }}</h3>
                                        <div class="progress" style="width: 50vw;">
                                            <div class="progress-bar bg-success"
                                                 :style="{width: file.upload.progress + '%'}"></div>
                                        </div>
                                        <pre>{{ file | json }} </pre>
                                    </div>
                                </div>
                            </div>
                        </template>
                    </vue-transmit>
                </div>
.............................
</template>
`
All of that I have inside .vue file.

**Comment by alexsasharegan** [comment]
So it looks like you're calling the handler function ` startUploadProcess` rather than passing it to be bound as a handler. Remove the parens: ` v-on:sending="startUploadProcess"`

**Comment by sergeypoprovka** [comment]
But it's the separate function I need to use there. This function is working normally.
But you have an emitter called 'upload-progress' that gives upload process percentage that I want to fetch inside my parent component. The only thing is wrong there as I see now is that I've destroyed this element on sending with v-if. Now I'm using v-show, but have the same result. 
Still can't fetch emitted value from 'upload-progress'

**Comment by alexsasharegan** [comment]
Are you saying the function is not defined on the vue component? I would make it a method on your component since vue resolves the functions with `this` as the vue component.

```js
Vue.component('uploader', {
  methods: {
    startUploadProgress: startUploadProgress
  }
})
```

Trust me, you shouldn't be calling that function in your template. It will be evaluated in the moment the template is evaluated rather than being called by vue-transmit in the upload life cycle.

**Comment by sergeypoprovka** [comment]
Nah...I have this function in my template and it's 'startUploadProCess' and not 'ProGress' ;) And it's separate function that not depends on your component at all ;)

**Comment by alexsasharegan** [comment]
Not sure if this will help, but here's a quick impl that watches all the lifecycle events:

```js
Vue.use(VueTransmit)
Vue.use(vueFlex)
window.app = new Vue({
	el: "#app",
	data: {
		options: {
			acceptedFileTypes: ["image/*"],
			url: "./upload.php",
			clickable: false,
		},
		files: [],
		showModal: false,
		error: "",
	},
	methods: {
		triggerBrowse() {
			this.$refs.uploader.triggerBrowseFiles()
		},
		onUploadSuccess(file, res) {
			console.log(res)
			file.src = res.url
			this.files.push(file)
		},
		onError(file, errorMsg) {
			this.error = errorMsg
			this.showModal = true
		},
		listen(event) {
			this.$refs.uploader.$on(event, function() {
				console.log(event, ...arguments)
			})
		},
	},
	filters: {
		json(value) {
			return JSON.stringify(value, null, 2)
		},
	},
	mounted() {
		;[
			"drop",
			"drag-start",
			"drag-end",
			"drag-enter",
			"drag-over",
			"drag-leave",
			"accepted-file",
			"rejected-file",
			"accept-complete",
			"added-file",
			"added-files",
			"removed-file",
			"thumbnail",
			"error",
			"error-multiple",
			"processing",
			"processing-multiple",
			"upload-progress",
			"total-upload-progress",
			"sending",
			"sending-multiple",
			"success",
			"success-multiple",
			"canceled",
			"canceled-multiple",
			"complete",
			"complete-multiple",
			"reset",
			"max-files-exceeded",
			"max-files-reached",
			"queue-complete",
		].forEach(this.listen)
	},
})
```

![image](https://user-images.githubusercontent.com/16269252/33287410-cf159b0c-d375-11e7-84b8-d9f260c68e7e.png)

**Comment by sergeypoprovka** [comment]
Actually, that does help! 👍  AWESOME! Thanks :)

`
this.$refs.uploader.$on('upload-progress', function(event) {})
`
Having this inside mounted() is what I need :)

**Comment by alexsasharegan** [comment]
Great! Not sure if I was fully understanding. Let me know if it works!

**Comment by sergeypoprovka** [comment]
YES! It works great! Thanks for the awesome component! :)

**Comment by alexsasharegan** [comment]
Excellent! You're welcome!
