### ISSUE TITLE
File rename

### ISSUE THREAD

**Issue by jjag3r** [alexsasharegan/vue-transmit#14]
How to rename the file before upload? I need to clean the file URL.

Thank you, Jure

**Comment by alexsasharegan** [comment]
There's a `renameFile` prop you can pass to the component. It's a function that takes a filename and returns a new filename:
<img width="899" alt="image" src="https://user-images.githubusercontent.com/16269252/33329256-5c46273c-d419-11e7-833c-66be9d09ca9a.png">

The default is an `identity` function, so it just returns the same name that it's given.

### Prop Definition
https://github.com/alexsasharegan/vue-transmit/blob/master/src/components/VueTransmit.vue#L235

### Usage
https://github.com/alexsasharegan/vue-transmit/blob/master/src/components/VueTransmit.vue#L629
