### ISSUE TITLE
Access files inside default slot

### ISSUE THREAD

**Issue by sourenaraya** [alexsasharegan/vue-transmit#16]
Is there a way to:
1) make entrie _body_ dropzone (listen to dragenter, dragleave, etc)
2) place files _inside_ default slot

**Comment by alexsasharegan** [comment]
@sourenaraya,

1. I personally would not recommend making your document a drop target, but you could set up your own event listeners and proxy everything off to `vue-transmit`. It's a bit of a tedious process, as you have to also set up proper tear down unless your component will never be destroyed.
  ```js
// somewhere in the component that sets up vue-transmit{
{
	data() {
		return {
			myListeners: [],
		}
	},
	mounted() {
		let vt = this.$refs.vueTransmit
		let body = document.body
		// Higher Order Function to wrap a listener and call
		// e.preventDefault() & e.stopPropagation(), then call the handler.
		let ePreventStop = fn => {
			return e => e.preventDefault(), e.stopPropagation(), fn(e)
		}
		let evt = "dragend"
		let fn = vt.handleDragEnd
		let rmListener = (eventName, handler) => () => body.removeEventListener(eventName, handler)

		body.addEventListener(evt, fn)
		this.myListeners.push(rmListener(evt, fn))
		evt = "dragenter"
		fn = ePreventStop(vt.handleDragEnter)
		body.addEventListener(evt, fn)
		this.myListeners.push(rmListener(evt, fn))
		evt = "dragover"
		fn = ePreventStop(vt.handleDragOver)
		body.addEventListener(evt, fn)
		this.myListeners.push(rmListener(evt, fn))
		evt = "dragleave"
		fn = vt.handleDragLeave
		body.addEventListener(evt, fn)
		this.myListeners.push(rmListener(evt, fn))
		evt = "drop"
		fn = ePreventStop(vt.handleDrop)
		body.addEventListener(evt, fn)
		this.myListeners.push(rmListener(evt, fn))
	},

	destroy() {
		let rm
		while ((rm = this.myListeners.shift())) {
			rm()
		}
	},
}
  ```
1. If you need to access files inside the default slot, you could always listen for the `added-file` event and then push a reference to that `VTransmitFile` object into an array on your component data. Then you'll have access to the files inside the default slot as they are added.

**Comment by sourenaraya** [comment]
Thanks!

Fun fact (about accessing files outside `files` slot): last image wont get dataUrl (until another one added) if progress-bar not rendered.

**Comment by alexsasharegan** [comment]
Everything is done async, so unless there's a bug, you're likely reading the dataurl before it's created. Listen for the thumbnail event and pluck them off then. Keep in mind too that the canvas api can't generate thumbnails for all image types (tiff files namely, but also files exceeding a size limit).

Let me know if you can't get that to work because I would consider it a bug otherwise.

**Comment by sourenaraya** [comment]
Tried to reproduce this behaviour on codepen, but everything works fine.  ¯\_(ツ)_/¯
https://codepen.io/anon/pen/jYONBW copy-paste from the docs
https://codepen.io/anon/pen/OzJLgK files outside `files` slot
https://codepen.io/anon/pen/LeYPeB no progress bar

**Comment by alexsasharegan** [comment]
Well that's interesting... I would say try adding a debugger, but that usually leads to a rather frustrating and unsolicited exploration of vue internals mixed with transpiler indirection. I think I'm right there with you 🤷‍♂️

**Comment by alexsasharegan** [comment]
I believe this is resolved. Feel free to reopen with more questions!
