### ISSUE TITLE
Dragged File not accepted in Chrome 63

### ISSUE THREAD

**Issue by beeches** [alexsasharegan/vue-transmit#17]
Hi,

I'm having trouble uploading files that were dropped on the dropzone. Adding the exact same .csv file via the file dialog works fine.

This is my options object: 

                options: {
                    acceptedFileTypes: ['text/csv'],
                    url: '//localhost:4567/order',
                    clickable: false,
                    maxFileSize: 10,
                    maxFiles: 1,
                    paramName: 'upload',
                    autoProcessQueue: false
                }

Might be related to this issue: https://github.com/enyo/dropzone/issues/1640

Thanks for having a look!

**Comment by alexsasharegan** [comment]
So if I understand correctly, the uploader works via file browser, but csv files aren't dragging and dropping? Which browsers don't work?

I don't believe the .map issue will be related. I handle file lists a little differently than mainline dropzone.

I'll try to reproduce this and investigate.

**Comment by beeches** [comment]
Yes, you got it right. When dropping the exact same file the 
Chrome 63 doesn't work.
FF 57.0.1 does work.
Both MacOS 10.12.6

console.log of the error event when dropping the file:

```
{
    "_nativeFile": {},
    "id": "v-transmit-file-3",
    "accepted": false,
    "lastModified": 1513170664000,
    "lastModifiedDate": "2017-12-13T13:11:04.000Z",
    "name": "test_auftrag.csv",
    "size": 661,
    "status": "error",
    "type": "",
    "upload": {
        "bytesSent": 0,
        "progress": 0,
        "total": 661,
        "speed": {},
        "end": 1513257816727,
        "time": null
    },
    "webkitRelativePath": ""
}
```

console.log of the success event when dropping the file:

```
{
    "_nativeFile": {},
    "id": "v-transmit-file-4",
    "accepted": true,
    "lastModified": 1513170664000,
    "lastModifiedDate": "2017-12-13T13:11:04.000Z",
    "name": "test_auftrag.csv",
    "processing": true,
    "size": 661,
    "status": "success",
    "type": "text/csv",
    "upload": {
        "bytesSent": 851,
        "progress": 100,
        "total": 851,
        "speed": {
            "kbps": 206.3,
            "mbps": 0.21
        },
        "start": 1513257883963,
        "end": 1513257883996,
        "time": 0.033
    },
    "webkitRelativePath": "",
    "xhr": {}
}
```

**Comment by alexsasharegan** [comment]
The file isn't picking up the mime type in chrome for some reason. Let me check a couple browser specific execution paths.

**Comment by alexsasharegan** [comment]
@beeches try `v7.1.3` and see if this is resolved.

**Comment by beeches** [comment]
Works like a charme! 

Thank you for the quick fix. 👍🏻
