### ISSUE TITLE
[Vue warn]: $attrs is readonly. $listeneres is readonly

### ISSUE THREAD

**Issue by sedyshev-a** [alexsasharegan/vue-transmit#19]
Hello!
I have issue with vue-transmit like this: https://github.com/apertureless/vue-chartjs/issues/151
https://github.com/apertureless/vue-chartjs/issues/201
https://forum.vuejs.org/t/vue-warn-attrs-is-readonly/18053/8

Every time the component itself or one of the parent components is updated, I get warnings in the console:

`[Vue warn]: $attrs is readonly.
[Vue warn]: $listeners is readonly.
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "uploadAreaClasses"`

**Comment by alexsasharegan** [comment]
Can you provide the contents of the component you're working on, or even better, a reproduction on codepen/jsfiddle?

**Comment by sedyshev-a** [comment]
I tried to reproduce this on webpackbin, but did't receive any warnings.
My component is just a wrapper over vue-transmit
```<template>
  <vue-transmit
    class="file-upload"
    v-bind="props"
    :uploadAreaClasses="['upload-area']"
    @added-file="onAddFile"
   ref="transmit">
    <slot>
      <h4 class="text-center">Files</h4>
      <btn type="primary" size="sm" class="mb-10"><i class="fa fa-folder-open mr-10" aria-hidden="true"></i>Browse</btn>
    </slot>
  </vue-transmit>
</template>

<script>
  import Vue from 'vue'
  import VueTransmit from 'vue-transmit'
  import 'vue-transmit/dist/vue-transmit.css'
  Vue.use(VueTransmit)

  import { Btn } from 'uiv'
  import getIconPathByMime from '@/helpers/mimeTypes'
  import _cloneDeep from 'lodash/cloneDeep'
  import _omit from 'lodash/omit'

  import EventBus from '@/helpers/bus'

  export default {
    props: {
      value: {
        type: Array,
        default: () => []
      },
      url: {
        type: String,
        required: true
      },
      thumbnailWidth: {
        type: Number,
        default: 40
      },
      thumbnailHeight: {
        type: Number,
        default: 40
      }
    },
    components: {
      Btn
    },
    data () {
      return {
        files: []
      }
    },
    computed: {
      props () {
        const props = _omit(this.$props, 'value')
        return {...this.$attrs, ...props}
      }
    },
    methods: {
      onAddFile (vFile) {
        let file = _cloneDeep(vFile)
        if (!file.type.match(/image.*/)) {
          file.dataUrl = getIconPathByMime(file.type)
        }
        this.files.unshift(file)
      },
    },
    watch: {
      files () {
        this.$emit('input', this.files)
      }
    },
  }
</script>
```
Note: computed value "props" does not affect the warnings in any way.

I think the problem is that there are two vue.esm.js (with different hashes) at the same time:
![image](https://user-images.githubusercontent.com/9392224/34359745-c047f176-ea6b-11e7-8a23-b7ecec548786.png)

**Comment by iec989** [comment]
I used the example in the Readme, and I got the same warnings.

I've updated Vue to the latest version, but still getting this warning.

Things seem to work fine though...

**Comment by alexsasharegan** [comment]
Looking through some of the related links you provided, I can see how you came to the two `vue.esm` bundles. I have vue set up as a dependency right now, perhaps I should drop it and use a peer dependency.

**Comment by alexsasharegan** [comment]
It looks like I can require `vue` as a dev dependency and keep the typescript compiler & build happy. This should ensure we aren't dealing with an error from duplicate vue bundles. Give `7.1.5` a try and see if that clears this up.

**Comment by sedyshev-a** [comment]
@alexsasharegan in my case both vue versions are the same. But updating to 7.1.5 closed the issue for me. There are no warnings now.
Thanks for very fast response!

**Comment by iec989** [comment]
Working fine to me too - cheers

**Comment by alexsasharegan** [comment]
Awesome! Thank you guys for helping clear this bug!

**Comment by DavidRamos015** [comment]
that happens  to me when I got more than one "single file component" with the same name

**Comment by alexsasharegan** [comment]
Are you saying this issue is affecting you? If so, what version are you running? Try running the latest v8 for the build fix for this issue.

**Comment by ronny332** [comment]
In my case the issue is happing with the latest v9 alpha 11.
Very strange to see is the fact, that it is happing only on my macbook pro, not on the mainly used iMac.
Both systems are identical, sharing the same code base.

**Comment by alexsasharegan** [comment]
Sounds like you might want to nuke the `node_modules` and do a fresh install. This issue seems to be centered around multiple vuejs deps getting bundled, so there must be another in there somewhere.

**Comment by ronny332** [comment]
Yes, that what I did again a few seconds ago. I kicked the node_modules folder and the whole cache at ~/.npm. The issue still exists.
I will try to dive a bit deeper into the issue.

**Comment by alexsasharegan** [comment]
This might be my bad. Let me go over the rollup config to make sure vue is an external dep. I'm also going to put a peer dep entry in the package.json.

**Comment by alexsasharegan** [comment]
Looks like the transpiled output is importing Vue properly for the two builds. Let me know what you find. I'm fairly certain that this is build related, not a component logic bug.

**Comment by ronny332** [comment]
The created files are identical. Both have a size of 51835 bytes, using `cmp` in the terminal does not show any differences between the files.
That's now a bit hard for me 😄. The vue version are identical, too. Everything seems to have the same base. What a mess.

**Comment by alexsasharegan** [comment]
Well that's interesting. Any browser extensions you have different that might do their own thing? I know this must seem basic, but have you checked the network tab to make sure another bundle of js isn't being loaded with more vue? I'm hitting a wall here for possibilities. If there was a way to reproduce it, I could check it out myself.

**Comment by ronny332** [comment]
Yeah, got it ... or maybe let me better say "found a way to reproduce it":

To build the module I have to install cross-env, which creates a folder node_modules within vue-transmit. The created files are all identical, the dist folders from the working and not working versions are replaceable with each other .
After removing the node_modules folder from the not working version, it works.

You can trust me, I don't know if laughing or crying is the best solution to accept this.

**Comment by alexsasharegan** [comment]
Is your project publicly visible by any chance? Are you building from source? I can mostly follow your explanation, but I'm not 100% tracking to where I could do it on my machine. The module should be built when you npm install it.

I definitely want to help you avoid that crazy solution!

**Comment by ronny332** [comment]
No, the project is not public, sorry for that.

The module does not build automatically. To reproduce this, a empty folder is enough:

```
➜  Temp mkdir transTest
➜  Temp cd transTest 
➜  transTest npm install https://github.com/alexsasharegan/vue-transmit/tarball/master

+ vue-transmit@9.0.0-alpha.11
added 1 package in 7.445s
➜  transTest ls -l ./node_modules/vue-transmit 
total 840
-rw-r--r--  1 noname  staff   15960 Mar 11 05:01 CHANGELOG.md
-rw-r--r--  1 noname  staff    3224 Mar 11 05:01 CODE_OF_CONDUCT.md
-rw-r--r--  1 noname  staff    1067 Mar 11 05:01 LICENSE
-rw-r--r--  1 noname  staff   31069 Mar 11 05:01 README.md
drwxr-xr-x  6 noname  staff     192 Mar 12 23:24 docs
-rw-r--r--  1 noname  staff     388 Mar 11 05:01 index.ts
-rw-r--r--  1 noname  staff     353 Mar 11 05:01 index.umd.ts
-rw-r--r--  1 noname  staff  349428 Mar 11 05:01 package-lock.json
-rw-r--r--  1 noname  staff    3729 Mar 12 23:24 package.json
-rw-r--r--  1 noname  staff    1319 Mar 11 05:01 rollup.config.js
drwxr-xr-x  4 noname  staff     128 Mar 12 23:24 scripts
drwxr-xr-x  8 noname  staff     256 Mar 12 23:24 src
drwxr-xr-x  9 noname  staff     288 Mar 12 23:24 test
-rw-r--r--  1 noname  staff     725 Mar 11 05:01 tsconfig.json
```

The dist folder is missing, no dependencies are installed automatically.

**Comment by alexsasharegan** [comment]
Ah, well this is built for distro on npm. That could be the issue there. Can you use npm for your install?

```sh
➜  vue-transmit-test npm i vue-transmit@9.0.0-alpha.11
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN vue-transmit-test@1.0.0 No description
npm WARN vue-transmit-test@1.0.0 No repository field.

+ vue-transmit@9.0.0-alpha.11
added 1 package in 0.565s
➜  vue-transmit-test tree -L 4
.
├── node_modules
│   └── vue-transmit
│       ├── CHANGELOG.md
│       ├── LICENSE
│       ├── README.md
│       ├── dist
│       │   ├── index.d.ts
│       │   ├── index.umd.d.ts
│       │   ├── src
│       │   ├── vue-transmit.css
│       │   ├── vue-transmit.esm.js
│       │   ├── vue-transmit.esm.js.map
│       │   ├── vue-transmit.esm.min.js
│       │   ├── vue-transmit.esm.min.js.map
│       │   ├── vue-transmit.js
│       │   ├── vue-transmit.js.map
│       │   ├── vue-transmit.min.js
│       │   └── vue-transmit.min.js.map
│       └── package.json
├── package-lock.json
└── package.json

4 directories, 17 files
```

**Comment by ronny332** [comment]
Yes, avoiding GitHub does the trick. Sorry for wasting your time, but as many projects do not upload the alpha or even beta versions to npmjs.org, I'm used to access GitHub directly and edit the package.json file if the final release is avaialble.

Maybe DavidRamos015 used the same wrong way and can solve his issue now, too.

But anyway, I will try to find out why the existence of the node_modules folder breaks the module. I'm using webpack to bundle everything, but webpack should not touch the node_modules folder within vue-transmit (but seemingly it does).

Thanks for your support!

**Comment by alexsasharegan** [comment]
Awesome! I do publish everything to npm since it's easy enough to do with standard version. I noticed the alpha versions don't show up when you `npm show vue-transmit` though.

**Comment by Tahywoh** [comment]
Good morning, I seem to be having the same issue here

**Comment by Tahywoh** [comment]
I am having that very error in about three components. But, this is the snippets of one of the component:

<template>
  <div class="registrationInstructions" id="registrationInstructions">
    <navbar/>
    <div class="row">
      <h3 class="text-center center-align application header" style="font-weight: 500;"></h3>
      <div class="regContent col m4 l5 hide-on-small-only show-on-med-and-up">
        <ul class="section table-of-contents">
          <h4>&nbsp;Contents</h4>
          <hr/>
            <li><a href="#requirements">Call for Entry</a></li>
            <li><a href="#applicants">Who can apply</a></li>
            <li><a href="#provisions">Provision for disabled</a></li>
            <li><a href="#closingDate">Application closing date</a></li>
            <li><a href="#fquestions">Have further questions?</a></li>
            <li><a href="#applyNow">How to apply?</a></li>
          </ul>
      </div>
      <div class="regContent col m8 s10 offset-s1 z-depth-2 l7 offset-l4" style=" padding: 2rem;">
        <hr/>
        <div class="appRequirements section scrollspy" id="requirements">
          <h4 class="left-align">Call for Entry</h4>
          <p class="requirementText">
            
            <ul>
              <li>College</li>
              <li>Polytechnic</li>
              <li>Undergraduate</li>
            </ul>
          </p>
        </div>
        <hr style="width: 70%; float: left"/><br/>
        <div class="applicants section scrollspy" id="applicants">
          <h4 class="left-align">Who can apply?</h4>
          <p class="appicantsText">
            <ul class="section table-of-contents">
              <li>Application is open to students in all fields</li>
              <li>Students of any registered instutions within africa</li>
              <li>Application is not restricted to any levels of higher learning. That is, it is opened to students from all levels or classes of any tertiary institutions.</li>
            </ul>
          </p>
        </div>
        <hr style="width: 70%; float: left"/><br/>
        <div class="provision-for-disables section scrollspy" id="provision">
          <h4 class="left-align">Provision for disabled</h4>
          <p class="provisionText">
           There is provision for disabled as the application is opened to all qualified candidates.
          </p>
        </div>
        <hr style="width: 70%; float: left"/><br/>
        <div class="fquestions section scrollspy" id="fquestions">
          <h4 class="left-align">Have further questions?</h4>
          <p class="appicantsText">
           Do you have further questions or having trouble applying? Kindly mail us at: <br/><a href="mailto:support@pmg-c.org">Support@pmg-c.org </a>
          </p>
        </div>
        <hr style="width: 70%; float: left"/><br/>
        <div class="closing-date section scrollspy" id="closingDate">
          <h4 class="left-align">Application Closing Date</h4>
          <p class="appicantsText">
           
          </p>
        </div>
        <hr style="width: 70%; float: left"/><br/>
        <div class="applyNow section scrollspy" id="applyNow">
          <h4 class="left-align">How to Apply?</h4>
          <p class="appyText">
            Click the button below to proceed.
          </p>
          <router-link :to="toRegistration" class="btn blue center-align text-center white-text">Proceed</router-link>
        </div>
      </div>
    </div>
    <footer-page/>
    <router-view></router-view>
  </div>
</template>

<script>
import Navbar from '@/components/layouts/navbar'
import FooterPage from '@/components/layouts/footer-page'
export default {
  components: {Navbar, FooterPage},
  mounted () {
    var scrolSelect = document.querySelector('.scrollspy')
    // eslint-disable-next-line
    var instance = new M.ScrollSpy(scrolSelect, {
      activeClass: 'active'
    })
    let newPath = this.$route.fullPath
    if (newPath.split('-')[5]) {
      newPath = newPath.split('-')[5]
      // console.log(newPath.split('-'))
      this.toRegistration = `/platinum-reasoning-contest-2018/register-candidate-${newPath}`
    }
  },
  data () {
    return {
      toRegistration: `/platinum-reasoning-contest-2018/register-candidate`
    }
  }
}
</script>

<style>
  h3.text-center.center-align.header.application {
    font-size: 2rem;
  }
  div.registrationInstructions > div.row {
    padding-top: 0%;
  }
  div.registrationInstructions > div.row > div.regContent.col.m4.l5 > ul > li > a {
    font-size: 16.5px
  }
  div.registrationInstructions > div.row > div.regContent.col.m4.l5 > ul.table-of-contents > li {
    padding: 3px 0;
  }
  div.registrationInstructions > div.row > div.regContent.col.m4.l5 > ul.table-of-contents {
    position: absolute;
    padding-top: 0rem;
  }
  /* div.registrationInstructions > div.row > div.regContent.col.m4.l5.hide-on-small-only > ul > li > a.active, div.registrationInstructions > div.row > div.regContent.col.m4.l5.hide-on-small-only > ul > li > a.active {
    font-weight: 600;
  } */
  /* div.registrationInstructions > div.navbar > nav {
    position: fixed;
  } */
</style>

Thanks as i await your response.

**Comment by alexsasharegan** [comment]
Can you confirm this is happening in Vue transmit? Maybe comment out the component and run back through the error reproduction. If so, can you include the error and a screenshot?

**Comment by Tahywoh** [comment]
If i route through it via click event, it will not display the error. However if i enter the direct url, it does.

**Comment by alexsasharegan** [comment]
Unfortunately, there's still not enough information for me to offer any suggestions. I would recommend making a jsfiddle/codesandbox/etc. reproduction of the bug.

One suggestion I can give purely on a hunch from working with this previously: make sure you aren't importing two versions of vue. This can happen if you require the production runtime vs. production with template compiler vs. dev runtime. Check all your `import Vue from 'x';` statements and ensure they are all the same. If that checks out, do a search in your `package-lock.json` for `vue` and make sure you only find one version resolved in there.

**Comment by Tahywoh** [comment]
Ok, i will do the checking  now

**Comment by Tahywoh** [comment]
There is only one version of vue there

**Comment by Tahywoh** [comment]
When i tried to comment the navbar component i called, this is the error i get in addition to the first one:

prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "to"

found in

---> <RouterLink>
       <RegInstructions> at src\pmgc\registration\regInstructions.vue
         <App> at src\App.vue
           <Root>

**Comment by alexsasharegan** [comment]
That sounds like an issue mutation props, not with vue-transmit.

**Comment by Tahywoh** [comment]
Here is the snippets once again
[regInstructions .txt](https://github.com/alexsasharegan/vue-transmit/files/2032912/regInstructions.txt)

**Comment by alexsasharegan** [comment]
Based on the message you posted, a route's `to` prop is being mutated. The stack trace and message appear incomplete though, so I still don't entirely trust what I'm looking at.

Here's the deal, until there's enough information, there's nothing I can do to help you. Try using a `debugger` statement in your code somewhere right before the error is triggered. Step through and see what you can learn.

**Comment by Tahywoh** [comment]
Hmmm, i have done that. I have figured out the reason behind it. Thanks

**Comment by Tahywoh** [comment]
Thanks for immediate response.

**Comment by Tahywoh** [comment]
But, i do have another little issue here. Can i proceed?

**Comment by alexsasharegan** [comment]
Sure, just please leave lots of information. Also, if it's off-topic for this issue, I would appreciate it being filed as a new issue. This helps other users who may encounter your issue find the correct thread.

**Comment by Tahywoh** [comment]
But how do i ensure you will see it and you will be the one to answer it?

**Comment by Tahywoh** [comment]
I have created it: https://github.com/alexsasharegan/vue-transmit/issues/55

**Comment by 9760** [comment]
这个问题os easy。是编译的时候出现的问题，你把.electron-vue里的webpack.renderer.config.js里的21行let whiteListedModules = ['vue']注释掉，以及28行的externals也注释掉就可以了，也不会报错了。

**Comment by getflourish** [comment]
Thanks @9760, works for me.

I’ll translate for everyone else:

> In `.electron-vue/webpack.renderer.config.js`, comment out `let whiteListedModules = ['vue']` and the `externals` definition in line 28.

**Comment by christoferd** [comment]
I fixed this warning: Vue warn $attrs is readonly. found in <RouterLink>
by _removing_ line: `import Vue from 'vue'`
while _keeping_: `import VueRouter from 'vue-router'`

Reason why it fixed: vue was being loaded twice.
