### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by iec989** [alexsasharegan/vue-transmit#20]
When uploading 5 files on a vue-transmit with the property maxFiles set to 3, I get 2 calls to the event _error_ and no calls to the event _error-multiple_. When is _error-multiple_ exactly firing?

Also, can I use regular Dropzone methods like _removeFile_ or _removeAllFiles_?

And a final dumb question - how can I access the files that are in the drop zone, from any method in the component? There is no v-model in the vue-transmit component. I may want to access those with errors so I can loop them and retry the upload. Should I push them into an array when _added-files_ is triggered?
By the way, to retry the upload, should I remove them and add them again using the _addFile()_ Dropzone method?

Thanks

**Comment by alexsasharegan** [comment]
## Error Multiple
A quick glance shows that this only fires when the `uploadMultiple` flag is set to true. This goes back to the original dropzone setup of sending either one XHR per file, or one large XHR (uploadMultiple).

## Removing Files
There are methods on the component for both `removeFile` and `removeAllFiles`. You can view the screenshots with line numbers to see the call signature.

## Vue-Transmit Data Access
I personally use the `added-file` hook for pushing files into the parent component's data. The slot `files` binds all the files along with various computed slices of files based on status. You could always use a ref on your vue-transmit instance to access its data directly. Something like this from the parent component:

```js
// assuming: <vue-transmit ref="vtransmit" />
let vtFiles = this.$refs.vtransmit.files
// you could also set this up in a computed prop on your parent component.
{
  computed: {
    vtFiles() {
      return this.$refs.vtransmit.files
    }
  }
}
```

## Retry
Good question on the retry setup. This might be a good one to file as a separate issue for feature request 👍. I think currently you should remove the file from vue-transmit, then call `addFile` on vue-transmit with the native file object (which can be access on the vTransmitFile @ `file.nativeFile`). This would clear the file out the data and avoid bugs around the file status.

![screen shot 2017-12-26 at 11 43 21](https://user-images.githubusercontent.com/16269252/34362594-3a1999f8-ea32-11e7-855c-5e8e2692c18c.png)
![image](https://user-images.githubusercontent.com/16269252/34362619-78fa9eb0-ea32-11e7-8b0e-c8b3ee82ccd6.png)
![image](https://user-images.githubusercontent.com/16269252/34362688-0aceb77c-ea33-11e7-84b4-17985c8ea9f6.png)

**Comment by alexsasharegan** [comment]
I'm going to close this until further feedback. Let me know if that answers your questions, and if the retry use case is important to you, please add a feature request issue!
