### ISSUE TITLE
thumbnail not display properly when autoProcessQueue = false

### ISSUE THREAD

**Issue by mickaelmarin** [alexsasharegan/vue-transmit#21]
hi,

I need to disable autoProcessQueue but when I add file the thumbnail display only if I had another image or if drag and drop and image on the dragdrop area.
I can see the "src" attribute of thumbnail img tag is equal to unknown.

How to can I change this behavior  ?

thanks

**Comment by alexsasharegan** [comment]
The thumbnail processing is enqueued directly after the `added-file` event regardless of the value of `autoProcessQueue`. There are conditions that must be met to process a given file (prefs, type, & size). The thumbnail is generated asynchronously, so you must rely on the `thumbnail` event which will be called with the arguments listed in the event documentation (also pictured below). The thumbnail will be found on `file.dataUrl`.

![image](https://user-images.githubusercontent.com/16269252/34421107-852fe408-ebca-11e7-9ebd-6c726f853e5f.png)
![image](https://user-images.githubusercontent.com/16269252/34421247-6665ab4c-ebcb-11e7-820d-bcf4eb8f8643.png)

**Comment by alexsasharegan** [comment]
Let me know if you have further questions, otherwise I'll go ahead and close this.

**Comment by mickaelmarin** [comment]
thanks for your response and thanks for your work your vue component is awsome !!!
