### ISSUE TITLE
How to use cancel upload

### ISSUE THREAD

**Issue by ibrahimkoujar** [alexsasharegan/vue-transmit#22]
Hi
I want to make afile uploader with cancel upload option is that possible with this plugin
if yes then how?!

Thanks.

**Comment by alexsasharegan** [comment]
There is a method on the component called `cancelUpload` that takes the file you want to cancel. This would work best in the default mode, not `uploadMultiple` since you couldn't cancel a single file in a bundled upload (multiple files on one Ajax request).
