### ISSUE TITLE
How can I add files or images programmatically?

### ISSUE THREAD

**Issue by anasbakro** [alexsasharegan/vue-transmit#23]

**Comment by alexsasharegan** [comment]
User interaction is required to access the clients file system. You can programmatically open the file browser using a ref on the component and calling `triggerBrowseFiles`. File system access is one of the inherent browser firewalls, so I'm not sure much more can be done (let me know of any new APIs around this, but they probably won't have full support yet).

**Comment by anasbakro** [comment]
Thanks but I'm not talking about the client images, I have an image url on the server and I would like to display it on the vue-transmit so can I do that?

**Comment by alexsasharegan** [comment]
Sounds like you just need to use an image element: `<img src="{{url}}"/>`

**Comment by anasbakro** [comment]
Well I know I can do that but I mean can I use addFile Function or addFileItem or something that help adding a file (url, name and ID) using code, anyways thanks again, one more question how can I empty the form file input (Could I have access to it?).

**Comment by alexsasharegan** [comment]
Sorry, I'm not sure I really understand what you were wanting to do.

To access the file input, first add a ref to your vue-transmit component:

```html
<vue-transmit ref="vtransmit"></vue-transmit>
```

Now in your component, you can access the file input like so:

```js
this.$refs.vtransmit.inputEl
```

**Comment by anasbakro** [comment]
Thanks
