### ISSUE TITLE
Can't add the same file after it was removed

### ISSUE THREAD

**Issue by all-bear** [alexsasharegan/vue-transmit#25]
Hi,

The scenario to recreate is like this:

1. Add some file to the dropzone
2. Remove file from step 1
3. Try to add same file - in my case there is no response from dropzone at all

or you can try to 

1. Add some file to the dropzone
2. Try to add same file to the dropzone - in my case there is no response from dropzone at all

I suppose the reason is:

Lib watch for hidden file input change:
`components/VueTransmit.vue`:
```javascript
<input type="file"
		       ref="hiddenFileInput"
		       :multiple="multiple"
		       :style="fileInputStyles"
		       :class="[maxFilesReachedClass]"
		       :accept="filesToAccept"
		       :capture="capture"
		       @change="onFileInputChange">
```

When some file was added value of this input become equals to this file (value doesn't cleared after file was added)
Then file was removed by first scenario (value of hidden file input doesn't cleared)
I'm trying to add this file again but `change` event doesn't triggered because value of input is still the same

PS: I fix this locally by just clearing input value after `accepted-file` and `rejected-file`

---

Please let me know if you need more info from my side and also thanks for this plugin it's really cool :1st_place_medal:

**Comment by alexsasharegan** [comment]
To follow the repro steps, are you autoprocessing? When you say in step 1 to add a file to vue-transmit, does this go through the full upload process or get removed before it gets accepted?

**Comment by all-bear** [comment]
Okay, let me create a demo soon, I think it will be more helpful :)

**Comment by all-bear** [comment]
So let's start from the beginning, I'll try to explain the same by demo

----------------------------
Test Case 1:
1. Go to https://codesandbox.io/s/wk6ojvqrj7 (sandbox with demo)
2. Add some file to the dropzone
3. Remove this file (maybe there is problem in remove function initialization, but I was not able to find other way to do this, so I'm using `removeFile` method of `vue-transmit` component)
4. Try to add SAME file to the dropzone again

Expected Result:
- File should be added to the dropzone again
Current Result:
- Files is not added to the dropzone

Video: https://drive.google.com/file/d/1YfTocHOOf0w7S9gqg3mzg2U88PXfUmVN/view

----------------------------
Test Case 2:
1. Go to https://codesandbox.io/s/wk6ojvqrj7 (sandbox with demo, I've add some dummy server for file upload)
2. Add some file to the dropzone
3. Add same file again

Expected Result:
- File should be added to the dropzone again
Current Result:
- Files is not added to the dropzone

Video: https://drive.google.com/file/d/1jlgpiJllR2kVlTfY1CGz64fkAnAs62cG/view?usp=sharing
-----------------------------
So I think the reason of this issues is the same, we need to clear file input DOM element value, after file was processed by plugin and pushed to `files` array.

P.S: please let me know if you need more info from my side, or if you want I can prepare PR, and send it for review for you, thanks

**Comment by sourenaraya** [comment]
How do you add files to dropzone? Via file-browser or drag-n-drop?
In case of file-browser, chrome wont add same file again (2nd time in a row), but drag-n-drop works.

In firefox everything working as expected.

**Comment by alexsasharegan** [comment]
It looks like the codesandbox I get when following your links doesn't match your videos. Also, test 1 & 2 are the same. I've hacked around it a little bit and I can reproduce your issue in chrome (firefox is working as @sourenaraya said).

It seems this is partly Chrome's intended behavior (W3 spec). See here: https://stackoverflow.com/a/9156783/5893865. I suppose they deem it incorrect to continue to fire the onchange event for a duplicate file. The user hack is just to upload a different file in between. The dev hack seems to be to force the onchange handler to run.

```js
// <vue-transmit ref="uploader" />
this.$refs.uploader.onFileInputChange()
```

This scoops out all the files still in the input element and adds them to vue-transmit.

I'm not clear on where to go from here, since this is how the spec works. This doesn't quite feel like a bug, but more of a _gotcha_ and bad UX side-effect. I don't like it, but any ideas on what vue-transmit should be responsible for in this case?

**Comment by alexsasharegan** [comment]
By the way, are there any browsers besides Chrome that exhibit the same behavior? I've tested these except for Edge:

- [x] Chrome: ❌ 
- [x] Safari: ❌ 
- [x] Firefox: ✅ 
- [ ] Edge

**Comment by all-bear** [comment]
@sourenaraya hey, I'm using file browser, please check videos from my previous answer, all steps from test cases I was trying to cover by videos
I can confirm that drag-n-drop works fine

@alexsasharegan I'm not sure why condesandbox is doesn't match videos (the only one change that I was made after videos is add `:url` to the vue-transmit)

I'm pretty sure that we are talking about different things now.

Let me try to explain it a bit different way,
Can you please check the screensharing before video:

This is the same codesandbox, but with one difference and it's important, I've made hidden file input, that is used by dropzone visible and problem is in value of this input:

1. Add some file to the dropzone - the file name that I selected is _'Screenshot from 2017-12-07 15-16-34.png'_, so the value of that input becomes like name of the file, then change event was triggered and handled by vue-transmit plugin. **Issue is that when vue-transmit plugin handle change event, value of file input is still _'Screenshot from 2017-12-07 15-16-34.png'_.**
2. Add SAME file to the dropzone - the file name that I selected is 'Screenshot from 2017-12-07 15-16-34.png', it was like _'Screenshot from 2017-12-07 15-16-34.png'_ and become _'Screenshot from 2017-12-07 15-16-34.png'_ so change event will be not triggered, because there is no change in this step, that's why vue-transmit will not handle same file

The solution that I can offer is to clear value of file input at the bottom of function `addFile` from vue-transmit component, in this way change event will be triggered in step 2. and vue-transmit will handle same file

Does it make sense ?

**Comment by alexsasharegan** [comment]
We are talking about the same thing, and I watched all the videos. Unfortunately, clearing a file input is not as easy as it sounds. I'll continue looking, but it's always been very difficult to clear a file input in a x-platform way. Some of the hacks out there won't work particularly well with Vue.

**Comment by alexsasharegan** [comment]
It does look like wrapping the input in a form allows for a for reset in a friendly way. I'll look into that. I'll have to ensure the point at which I reset the form won't destroy any files that are added simultaneously though.

**Comment by all-bear** [comment]
Okay cool, thanks, I'm not well familiar with Vue so the only thing that I can do is report it for you about this issue and provide your info from my side :)

In my project it was enough to do this:

````javascript
this.$refs.uploader.inputEl.value = '';
```
on `accepted-file` event from vue-transmit

Thank you for feedback

**Comment by alexsasharegan** [comment]
@all-bear , go ahead and give `v8.0.0` a try and let me know if it solves the issue.

**Comment by all-bear** [comment]
@alexsasharegan cool thanks it works, I'm really appreciated for you help

**Comment by alexsasharegan** [comment]
Awesome! I'm glad we got this quirk fixed!
