### ISSUE TITLE
How to add already uploaded files like in DropzoneJS

### ISSUE THREAD

**Issue by maxcook** [alexsasharegan/vue-transmit#31]
So in DropzoneJS i can add  already uploaded files with this piece of code:

var mockFile = { name: "Image1", size: fileSize };
myDropzone.emit("addedfile", mockFile);
myDropzone.emit("thumbnail", mockFile, "images/img.jpg");
myDropzone.files.push(mockFile);

How can I prefill vue-transmit?

**Comment by maxcook** [comment]
seems as if this is enough:
this.$refs.uploader.files.push(mockFile);

while mockFile.dataUrl points to the url of the image

**Comment by alexsasharegan** [comment]
Yup, that's exactly how I would have done it!

**Comment by alexsasharegan** [comment]
By the way, you could probably use the existing VTransmitFile definition to build your mocks. `src/classes/VTransmitFile.ts`. Although if you're not using typescript, maybe not so fun.
