### ISSUE TITLE
How to "reset" props.files?

### ISSUE THREAD

**Issue by fbnlsr** [alexsasharegan/vue-transmit#32]
Hi there,

I'm using vue-transmit on a project, and I would like to "reset" the `files` slot which is shown in the example. I'm emitting a custom event once a file has been uploaded, and I'd like to use this even to trigger this cleanup. I've tried looking in the vue-transmit doc as well as in the vue doc but couldn't find a way to do so. Can anyone help me?

**Comment by alexsasharegan** [comment]
Do you want to clear the underlying file input, component data, or both?

**Comment by fbnlsr** [comment]
I'm using vue-transmit for blog image covers.

At first I think I'd like to clear the component data, for when a cover has been successfully uploaded.

Then, since I have a "remove cover" button, I guess I'd like to clear both the underlying file input and the component data.

**Comment by alexsasharegan** [comment]
I would personally recommend using vue-transmit to add those files to your own parent component's data where you have full control, but that certainly doesn't fit every use case. Just food for thought if you haven't considered it.

#### `VueTransmit.removeAllFiles(cancelInProgressUploads = false)`

This is the method you'll want to use to clear the component's data array of files. You can pass true to cancel any uploads that are in progress at the time of removal. To call this, place a `ref` on `<vue-transmit ref="vtransmit" />` inside your template, and then once the mounted hook is called, your ref will be populated:

```
this.$refs.vtransmit.removeAllFiles(true)
```

As for the file input, that is actually clear on every change event to avoid some browser implementation quirks. Each change event basically scoops out the files and put them in the component instead.

**Comment by alexsasharegan** [comment]
@fbnlsr, let me know if this solve your issue!

**Comment by fbnlsr** [comment]
@alexsasharegan hey sorry I wasn't able to test your solution as I was out for a few days. I've tried implementing your suggestion but I get an error in the console: `Error in event handler for "uploadedImage": "TypeError: this.$refs.vtransmit.removeAllFiles is not a function"`

I'm not sure how to deal with that error. 🤔

**Comment by alexsasharegan** [comment]
Can you drop in your component code? It's definitely a function, so something is going wrong elsewhere.

**Comment by fbnlsr** [comment]
I've put it in a gist, here: https://gist.github.com/fbnlsr/d6d45e825829c45319dba40faa84109a#file-postform-vue-L265

**Comment by fbnlsr** [comment]
Hey @alexsasharegan thank you so much for your time. Here is the partial: https://gist.github.com/fbnlsr/8aa610665584fd71d09e56d2e396e717

**Comment by fbnlsr** [comment]
I got it to work! I was thinking about what you wrote and you were right, I had to put the function inside my partial. Thanks again for your help! :)

**Comment by alexsasharegan** [comment]
Nice! Glad we were able to figure it out!

**Comment by fbnlsr** [comment]
@alexsasharegan I've just noticed something. It seems that if I try to upload a bunch of files, `removeAllFiles` also removes files that are waiting to be uploaded. It does not remove the files being currently uploaded thanks to its `false` argument flag but all the other files vanish. Is there another method that could empty only the finished uploaded files from the queue?

**Comment by alexsasharegan** [comment]
@fbnlsr, you can combine the filtered files arrays with the `removeFile` method to just remove the files you want. Here's all the filtered lists that you can choose from:

```js
let filesToDelete = [
  // copy the array values into your own array
  ...this.$refs.vtransmit.acceptedFiles,
  ...this.$refs.vtransmit.rejectedFiles,
  ...this.$refs.vtransmit.addedFiles,
  ...this.$refs.vtransmit.queuedFiles,
  ...this.$refs.vtransmit.uploadingFiles,
  ...this.$refs.vtransmit.activeFiles,
];

for (let file of filesToDelete) {
  this.$refs.vtransmit.removeFile(file)
}
```

**Comment by fbnlsr** [comment]
Thanks! Is there a filtered list for the succesfully uploaded files?

**Comment by alexsasharegan** [comment]
Hmm... there isn't. I'll add one. How does a method called `removeFilesWithStatus(...status: string[])` sound?

**Comment by fbnlsr** [comment]
That sounds perfect. We should be able to pass an array of different status as well, don't you think?

**Comment by alexsasharegan** [comment]
The `...` means it's a variadic function—it will accept any number of arguments.

```js
vm.removeFilesWithStatus('added', 'queued', 'uploading');
// if you have an array, just spread the array into arguments
vm.removeFilesWithStatus(...['added', 'queued', 'uploading']);
// or via the backwards compatible method
vm.removeFilesWithStatus.apply(vm, ['added', 'queued', 'uploading']);
```

**Comment by fbnlsr** [comment]
That sounds pretty good then! 👍

**Comment by alexsasharegan** [comment]
Are you using the beta version? Or version 8?

**Comment by fbnlsr** [comment]
We're using v8.0.0 atm but since we're still in the development phase of the app, we could switch to a beta version I guess.

**Comment by alexsasharegan** [comment]
I'll see if I can make the adjustment to 8 as well. I'll post back once I have a release.

**Comment by fbnlsr** [comment]
Awesome, thanks a lot!

**Comment by alexsasharegan** [comment]
Alrighty, `8.1.0` is available now. Try it out and let me know if it works!

**Comment by fbnlsr** [comment]
Hey @alexsasharegan  I completely forgot to keep you updated about this issue. The update you've pushed does the job perfectly. Thanks a lot! 👍

**Comment by alexsasharegan** [comment]
Awesome! Glad to hear it!
