### ISSUE TITLE
How to resize an image before accept?

### ISSUE THREAD

**Issue by rickyruiz** [alexsasharegan/vue-transmit#33]
**Question:**
Is it possible to resize an image or multiple images before creating the `VTransmitFile` instance(s)?

___
There is a `resizeImg` prop but this is a function that returns coordinates, which are later used to create the thumbnail.

I could probably use the `accept` function and replicate the  `createThumbnail` and `createThumbnailFromUrl` functionallity, what are your thoughts?

**Comment by alexsasharegan** [comment]
So my initial reaction is that resizing an image would require an operation on the underlying blob data of that image. This might be possible, but would definitely have performance implications if executed on a large file in the main thread.

I'll try to do a little investigation on this. I believe the blob is also an immutable native object, so hopefully one could create a blob from some function operating on the original. I'll let you know what I find. Post back if you find anything promising too.

**Comment by alexsasharegan** [comment]
I'm not done searching, but my initial finds are around using the canvas API to resize and create a blob. In my experience, this is very janky/slow, but I work with large files at my company (usually files exceed 50MB, but sometimes go as high as 500MB). What is your max file size here? And maybe give some background on the overall use case so I can put it in perspective.

On the canvas api, I believe the thumbnail code could be reused and instead of dumping a base64 encoded string, we could dump to a new blob. I frankly don't want to support that in the library, but I'm down for helping you find a good way to implement it.

**Comment by rickyruiz** [comment]
The max file size will be around 2MB, the client sends a request to a proxy and the proxy then sends a request to an API, I was thinking that sending a base64 encoded string would be easiest/fastest way to send the image across the project layers.

I will keep working on this tomorrow, I'll let you know what I did.  You may close this, the process will most probably be slow and not worth implementing: FileReader => Canvas => Base64 => Blob .. 

Thank you very much for your help, time and great library.

**Comment by alexsasharegan** [comment]
Okay, so then this should be doable. I also use a proxy server before hitting the destination server that manages the FS. Looks like the `File` constructor can take a blob and a name, and the canvas api has a `canvas.toBlob` method.

**Comment by alexsasharegan** [comment]
So I'll drop in some code below. I'm not exactly sure on the flow, but you could deny the file in the accept hook, but use that hook to kick off your own image processing with the code below to resize. The MDN reference says it renders at 96dpi, so not awesome quality. Anyways, the promise below resolves with a native file object. This is what you can call `addFile` with on the vue-transmit component instance. The trick here is you don't want to enter and endless loop with you accept hook. So maybe you rename the file with a custom prefix/suffix/id/regex? I've also pulled out the supporting functions used internally for thumbnails. Ideally you could just require those and compile from source, but that's hard to do with the typescript/vue combos. I say just dupe the code and call it.

<details>
<summary>Code</summary>


```js
export function scaleH(ratio, width) {
  return width / ratio;
}

export function scaleW(ratio, height) {
  return height * ratio;
}

export function resizeImg(file, dims) {
  // 's' variables are for source
  // 'd' variables are for destination
  const sRatio = file.width / file.height;
  const dRatio = dims.width / dims.height;
  const coords = {
    sx: 0,
    sy: 0,
    sWidth: file.width,
    sHeight: file.height,
    dx: 0,
    dy: 0,
    dWidth: dims.width,
    dHeight: dims.height,
  };

  let w, h;
  if (dRatio > sRatio) {
    w = file.width;
    h = scaleH(dRatio, file.width);
  } else {
    w = scaleW(dRatio, file.height);
    h = file.height;
  }

  if (w < file.width) {
    coords.sx = (file.width - w) / 2;
    coords.sWidth = w;
  }
  if (h < file.height) {
    coords.sy = (file.height - h) / 2;
    coords.sHeight = h;
  }

  return coords;
}

new Promise(resolve => {
  let ctx;
  file.width = imgEl.width;
  file.height = imgEl.height;
  const resizeInfo = this.resize(file, {
    width: this.thumbnailWidth,
    height: this.thumbnailHeight,
  });
  const canvas = document.createElement("canvas");
  // Can be null
  if (!(ctx = canvas.getContext("2d"))) {
    return;
  }

  canvas.width = resizeInfo.dWidth;
  canvas.height = resizeInfo.dHeight;
  ctx.drawImage(
    imgEl,
    resizeInfo.sx,
    resizeInfo.sy,
    resizeInfo.sWidth,
    resizeInfo.sHeight,
    resizeInfo.dx,
    resizeInfo.dy,
    resizeInfo.dWidth,
    resizeInfo.dHeight
  );

  let quality_coefficient = 1;
  canvas.toBlob(
    blob => resolve(new File(blob, file.name)),
    file.type,
    quality_coefficient
  );
});

this.$refs.vtransmit.addFile(native_file)
```

</details>

**Comment by alexsasharegan** [comment]
Sorry, this code is a bit hacked together. I've updated it a couple times, but that's pretty close to functional.

**Comment by alexsasharegan** [comment]
Hah... forgot the file reader.

**Comment by rickyruiz** [comment]
Thanks, since you were so kind to provide code I threw it all in a small demo. I did not organize anything and a lot of stuff is in a single method, but it works. I just added a boolean to prevent the endless loop.

Demo: [codesandbox](https://codesandbox.io/s/ovpx91q7zy)
