### ISSUE TITLE
Where is the demo/use case?

### ISSUE THREAD

**Issue by irjayjay** [alexsasharegan/vue-transmit#34]
Maybe I'm just not seeing it, but there are no demos/demo code?

I'm not really sure what all the props do or what the expected behaviour should be.

Is there codepen link somewhere?

**Comment by alexsasharegan** [comment]
I could definitely do better on this one, but you can look in the test directory for a live example. If you clone the repo, running npm install, npm run build, then npm test will spin up the php dev server and serve a test app.

I'll try adding a code pen or code sandbox shortly. Are you playing with v8, or the v9 alpha?

**Comment by irjayjay** [comment]
Ah, thank you, so it's meant to be cloned.

I'm trying v9. Took some trial and error, copied the code at the bottom of the readme. Seems it requires a url prop, which wasn't included. Also, couldn't get it to work by importing straight into my component, so I used it as a plugin globally with Vue.use()

**Comment by alexsasharegan** [comment]
Hmm, I'll check into the import issue. That's definitely something I want working. Did you see the different imports in the build section of the readme?

The URL prop goes in the adapter options. Basically I have an upcoming firebase adapter that will be an optional plugin to add. It's a tad more boilerplate for everyone else, but now you can write your own upload transport adapter as an es6 class.

**Comment by alexsasharegan** [comment]
Come to think of it, this refactor also enables a websocket transport. It also sounds the build lots!

**Comment by alexsasharegan** [comment]
*slims the build

**Comment by alexsasharegan** [comment]
Oh, so the URL in the component is defunct. I should remove that to confirm the components isn't requiring it as a leftover.

**Comment by alexsasharegan** [comment]
I added a code sandbox link in the readme. It's up top right after the main description. Feel free to check it out and report back here with feedback on how well it's working. The main problem is I can't connect a backend to receive the upload. Let me know if you know of a url I can point this thing at to make uploads to.

**Comment by rickyruiz** [comment]
@irjayjay If you are using v9 make sure to import it like so:

`import { VueTransmit } from 'vue-transmit';`

`VueTransmit` is not the default export. This may raise another question, why is `VueTransmit` not the default export in [here](https://github.com/alexsasharegan/vue-transmit/blob/master/index.ts).

In my opinion it would be easier and less confusing to import it like so:

`import VueTransmit from 'vue-transmit';`

You can still have it under named exports if needed.

```
import { PluginObject } from "vue";
import { VueTransmit } from "./src/index";
import { XHRUploadAdapter } from "./src/upload-adapters/xhr";

const VueTransmitPlugin: PluginObject<undefined> = {
  install(Vue) {
    Vue.component("VueTransmit", VueTransmit);
  },
  name: "vue-transmit",
};

export { VueTransmitPlugin, VueTransmit, XHRUploadAdapter };
export default VueTransmit;
```

**Comment by irjayjay** [comment]
Hi there. 

It seems that everything inside adapterOptions is ignored.
I just set some headers, had to see how it's done on dropzone.js and do it the same way. I just want to set the CSRF token, but it isn't added. The url in here also doesn't get used at all.

Where should I be adding these?

Also, with regards to you previous reply:

I uploaded in my component using:
import { VueTransmit } from 'vue-transmit';

and then adding
components: {
    "vue-transmit": VueTransmit,
},

But I got an error:

Unknown custom element: <vue-transmit> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by alexsasharegan** [comment]
So maybe you can help me with this, @rickyruiz. Using Rollup, it really doesn't like mixing and matching default exports with named exports. Before I put v9 in beta, I'll figure something out to offer a default export. For now I punted. I'm personally moving to using named exports over default exports always because there is a lot more power in the refactoring.

**Comment by irjayjay** [comment]
Anyway, what helped me in the end was just using:
`import VueTransmit from "vue-transmit";

var SocialSharing = require('vue-social-sharing');

Vue.use(VueTransmit)`

**Comment by alexsasharegan** [comment]
@irjayjay, if it's ignoring the adapterOptions, it must be downloading the v8 lib. That one has a default export.

**Comment by irjayjay** [comment]
Excuse my ignorance, but doing a yarn add doesn't add V9 by default then?

I just ran:

```
yarn add vue-transmit --save
```

**Comment by alexsasharegan** [comment]
Correct. Yarn still interacts with the npm registry the same. You would probably have to do this:

```sh
yarn add vue-transmit@9.0.0-alpha.7
```

Yarn will save as production dependency by default, but you can add `--save` if you like.

**Comment by alexsasharegan** [comment]
Alpha 7 is, roughly speaking, stable. I don't intend on changing anymore APIs. I do intend on adding a default export once I figure that out, and then iterating on a firebase adapter (no stability guarantees there). So we'll say this, alpha will remain stable for traditional XHR uploads barring any bugs that must be fixed.

**Comment by rickyruiz** [comment]
I will download PHP to spin up the server and give it a try as soon as I can @alexsasharegan , I'll let you know if I figure out a way.

**Comment by alexsasharegan** [comment]
You know, I might just make two entry point files. I'll make a UMD entry point that hangs everything off an object, and then an esm entry point that also exports default as the plugin. How does that sound, @rickyruiz ? Are you using this in a build chain like webpack? I guess what I'm asking is are you using ESM or UMD?

**Comment by rickyruiz** [comment]
Yeah I'm using webpack, having multiple entry points is what is suggested [here](https://github.com/rollup/rollup/issues/1044#issuecomment-253214545) as well.

**Comment by alexsasharegan** [comment]
Hah, would you look at that. I'm about to push a new alpha that will include this default export.

**Comment by alexsasharegan** [comment]
Done!

**Comment by alexsasharegan** [comment]
Rollup must have also added support for config as an array of configs to do multi output. Winning all around 🏅 🏅 🏅

**Comment by irjayjay** [comment]
By the way, how would I go about deleting an uploaded item?

**Comment by alexsasharegan** [comment]
Put a ref on the vue-transmit component, and then call removeFile on the instance.

```html
<template>
  <!-- add the ref -->
  <vue-transmit ref="vtransmit" />
</template>
```

```js
export default {
  methods: {
    deleteFile(vtFile) {
      this.$refs.vtransmit.removeFile(vtFile)
    }
  },
};
```

**Comment by alexsasharegan** [comment]
@irjayjay, feel free to open new issues for questions as you're diving in. I added an FAQ section since your last question is common. I'd like to use your fresh experience to fill out that FAQ section with info to make it easy to get started. Issues for each topic make it easy for me to reference later too.
