### ISSUE TITLE
Upload on submit button click, instead of immediate upload on "File Upload" button.

### ISSUE THREAD

**Issue by fnoori** [alexsasharegan/vue-transmit#37]
Is it possible to upload a file on a "submit" button click? As opposed to uploading immediately?

In my application, I have a form that accepts many text input fields and the image upload section. 

What I want to be able to do is when the "submit" button is clicked, the text field data is first added to my database (this also creates a unique ID), to which then I can use this unique ID to upload the image files to the correct directory (or create a new directory for the images, if one does not exists).

This is my code for the vue-transmit tag
``` html
<vue-transmit class="col-12" tag="section" v-bind="transmitOptions" :url="uploadUrl" upload-area-classes="bg-faded" ref="uploader">
    <div class="d-flex align-items-center justify-content-center w-100" style="height:50vh; border-radius: 1rem;">
    <button class="btn btn-primary" @click="triggerBrowse">Upload Files</button>
</div>
```

And this is my code for the `triggerBrowse`
```js
triggerBrowse() {
    this.uploadingVehiclePictures = 'hello'
    this.uploadUrl = 'http://localhost:3000/' + this.$store.state.dealershipLoggedIn + '/' + this.uploadingVehiclePictures + '/-1/pictures/'
    this.$refs.uploader.triggerBrowseFiles()
}
```

Now, what I want to happen is for the ```triggerBrowseFIles()``` to happen with the "Upload Image" button is clicked, but I do not want it to be immediately sent to my backend.

I want the image(s) to be sent to my backend when I click my "submit" button on the form.

If I were to change the ```@click="triggerBrowse"``` to my submit button handler, then ```triggerBrowseFiles()``` will not be called, but if I keep it as it is right now, the files are uploaded as soon as I choose a file from the file upload popup.

Maybe there is a different way of handling this, any help would be great !

**Comment by alexsasharegan** [comment]
Yes, there is definitely a way to do this. The default behavior of VueTransmit is to autoprocess everything, but you can disable this for uploads and thumbnails.

You'll want to choose one of two options: `autoProcessQueue` or `autoQueue`. Personally, I would pass `{ autoQueue: false }` in the options, and then call `processFile` manually once your server response comes back with the necessary information. This will ensure your dynamic url is used without incurring any race conditions—like another file coming back and updating the url before the previous file upload begins.

```html
<template>
  <vue-transmit class="col-12"
                tag="section"
                v-bind="transmitOptions"
                :url="uploadUrl"
                :auto-queue="false"
                upload-area-classes="bg-faded"
                @accept-complete="getUploadId"
                ref="uploader">
    <div class="d-flex align-items-center justify-content-center w-100"
         style="height:50vh; border-radius: 1rem;">
      <button class="btn btn-primary"
              @click="triggerBrowse">Upload Files</button>
    </div>
</template>

<script>
export default {
  data() {
    return {
      uploadUrl: "",
      transmitOptions: {},
    };
  },
  methods: {
    getUploadId(file) {
      axios.post("your/backend/url", { data: file }).then(response => {
        this.uploadingVehiclePictures = "hello";

        this.uploadUrl = `http://localhost:3000/${
          this.$store.state.dealershipLoggedIn
        }/${this.uploadingVehiclePictures}/-1/pictures/`;

        this.$refs.uploader.processFile(file);
      });
    },
  },
};
</script>
```

[Source Code](https://github.com/alexsasharegan/vue-transmit/blob/master/src/components/VueTransmit.vue#L198-L216)
![code](https://user-images.githubusercontent.com/16269252/36917240-8bd48cf2-1e13-11e8-9bb1-d4379d5c630e.png)

**Comment by fnoori** [comment]
Thank you for the in depth explanation and vue-transmit is an awesome library !

**Comment by alexsasharegan** [comment]
Thank you! I appreciate you taking the time to post a well-described issue. Feel free to open new issues for feature requests, usability, bugs and the like. It helps make this rock solid!
