### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by I2olanD** [alexsasharegan/vue-transmit#38]
Is it possible to introduce SSR Support for your Project?

**Comment by alexsasharegan** [comment]
It's definitely possible, but I'm unaware of the constraints. Do you have any references that could help me?

**Comment by alexsasharegan** [comment]
Setup code is in the `mounted` lifecycle hook, so it doesn't look like this component should be incompatible with SSR. I'll close it and you can reopen if you encounter any errors.
