### ISSUE TITLE
Disable drag on input fields inside component

### ISSUE THREAD

**Issue by dmitry-litviak** [alexsasharegan/vue-transmit#39]
Hi,

Is there any way to allow selection of text in input/textareas inside vue-transmit component?

To replicate the problem try to place input with the value inside vue-transmit component and select text. Codesandbox with issue - https://codesandbox.io/s/1yl0plv2nl

I am trying to make the whole form to be a dropzone and faced the problem, that there are no ways to select text inside inputs.

**Comment by alexsasharegan** [comment]
Stay by passing `clickable = false` into component options. If that doesn't work, you can add Vue inline event handlers like so: 

```html
<input @click.stop>
```

I'll take a look at the sandbox when I'm my computer.

**Comment by dmitry-litviak** [comment]
Thanks for quick response.

Both of these methods didn't work for me. Actually, I probably need not `@click`, but `@select`, but it didn't work too. 

So I will wait until you take a look at it.

**Comment by dmitry-litviak** [comment]
Seems, that I found the problem and solution. There is attribute `draggable="true"` at the main wrapper. If remove it - everything works fine. 

For now, I add this line to `mounted` method:

`document.querySelector('.v-transmit__upload-area').draggable = false;`

Is there any option to disable it? If not, can you add it in the future release?

**Comment by alexsasharegan** [comment]
Looks like the draggable attr is really hard to nuke without disabling other important UI bits. I'll definitely add a prop for disabling drag and drop.

You could maybe speed up the querySelector a tiny bit by executing it from the instance. Call it an improved hack.

```js
// from your consuming component
this.$refs.vtransmit.$el.querySelector('.v-transmit__upload-area').draggable = false;
```

I'll leave this open until I address it.

**Comment by alexsasharegan** [comment]
New versions out for v9 alpha and v8 stable that include a `disableDraggable` prop. Pass `true`, or use the boolean attribute style like so:

```html
<vue-transmit disable-draggable />
```
