### ISSUE TITLE
chrome corrupts when drag&droping files from open file dialog

### ISSUE THREAD

**Issue by KravtsovEgor** [alexsasharegan/vue-transmit#4]
# Issue
Chrome corrupts when drag&droping files from input's pop-up
# Expected
User can add files with drag&drop from the open file dialog as well as select them

**Comment by alexsasharegan** [comment]
Can you give some more info? This is used in production (at [artisanhd.com](https://artisanhd.com/secure/uploadconfigure/)) and all browsers are performing drag and drop correctly. Also, clicking the upload area successfully triggers the internal file input to show the native file browser.

Are you having issues with drag & drop, or with opening a file browser? What does _"Chrome corrupts"_ mean more specifically?

**Comment by KravtsovEgor** [comment]
The issue occurs time to time. I just open the native file browser and drop files from here, then I press cancel button and chrome does not respond until I reopen it. But I can't reproduce it every time, so I can't describe exactly which step provides the problem. The issue may be closed. I'll try to do the same tommorow on our stand. Sorry for the time spent

**Comment by alexsasharegan** [comment]
Do you use a mac with a window manager? I'm a magnet user, but also better touch tool users have a lot of issues with chrome and clicks _"missing"_. Just a shot in the dark, but if it lines up, quit those apps and see if the issue disappears.

**Comment by KravtsovEgor** [comment]
It's time to provide my config. I'm using desktop windows chrome.
`<vue-transmit class="col-12"
                      tag="section"
                      v-bind="options"
                      @sending-multiple = "beforeSend"
                      @complete-multiple = "completeSend"
                      @total-upload-progress = "totalProgressChanged"
                      @accepted-file = "filesAcceptedFunction"
                      @removed-file = "fileRemovedFunction"
                      ref="uploader">

options: {
        acceptedFileTypes: ['.xlsx', '.xls'],
        url: 'http://localhost:4567/upload',
        clickable: false,
        **autoProcessQueue: false,**
        maxConcurrentUploads: 100,
        uploadMultiple: true,
        maxFiles: 100
      }`

1. Click Choose files, which triggers **this.$refs.uploader.triggerBrowseFiles()**.
2. Drag&drop some files (2-8, it doesn't mind) from native browser window.
3. Click Cancel button in native browser window.
4. Delete files one by one using **this.$refs.uploader.removeFile(file)**. 
5. Repeat steps 1-4 from one to ten times and chrome browser shuts down (after step 3)

PS. I've tried to do the same in Firefox and everything works perfect.

**Comment by alexsasharegan** [comment]
Thanks for the details! I'll try to replicate and see what's going on. I've never tried drag & drop using the file browser triggered open before. I'll give it a try!

**Comment by alexsasharegan** [comment]
I haven't been able to reproduce this. Are you disabling the autoprocessing?

**Comment by KravtsovEgor** [comment]
yes, autoprocessing is disabled. I need to load all files in one request

**Comment by alexsasharegan** [comment]
Maybe drop in how you are processing the queue? Since I'm unable to reproduce the issue with auto-processing, it's possible something in there is related. I doubt it though because your steps _should_ occur before processing.

**Comment by alexsasharegan** [comment]
I'm going to close this pending further information or until another similar case pops up.
