### ISSUE TITLE
How to send X-WP-Nonce?

### ISSUE THREAD

**Issue by sorensenjg** [alexsasharegan/vue-transmit#41]
Trying to use this package with the wordpress rest api and can't figure out how to send the nonce through with the post request. Any help would be appreciated!

Example of how I'm successfully making this request via Axios:

import Axios from "axios";

Axios.defaults.baseURL = wpApiSettings.root + "wp/v2";
Axios.defaults.headers.common["X-WP-Nonce"] = wpApiSettings.nonce;

Axios.post("/media/", formData, { "Content-Disposition": "media" })

**Comment by alexsasharegan** [comment]
Which version are you running? The stable 8 branch or the pre release 9? I think in both cases there is an option for additional headers, but the option location changes based on the version. The header option in both cases is an object.

**Comment by sorensenjg** [comment]
@alexsasharegan 

Thanks, ill give this a try. I also realized last night I was using v9 docs with v8.

**Comment by sorensenjg** [comment]
Just to follow up, setting the nonce in the header worked perfectly. Thanks @alexsasharegan!

adapterOptions: {
     headers: { "X-WP-Nonce": wpApiSettings.nonce }
}

**Comment by alexsasharegan** [comment]
Excellent!
