### ISSUE TITLE
How to include CSS from component

### ISSUE THREAD

**Issue by benirose** [alexsasharegan/vue-transmit#45]
It seems like all the CSS supporting this is in an external file. Is it possible to import this file in my Vue single-file component?

**Comment by alexsasharegan** [comment]
It's completely optional, but here's the import statement you'll need:

```js
import 'vue-transmit/dist/vue-transmit.css';
```

**Comment by alexsasharegan** [comment]
You can see the css here too, btw: https://unpkg.com/vue-transmit@8.1.2/dist/vue-transmit.css

**Comment by benirose** [comment]
Do I put that in the `script` or `style` tag?

**Comment by benirose** [comment]
I assumed I needed this CSS file, since I don't see the dropzone on the page at the moment.

**Comment by alexsasharegan** [comment]
So if you have webpack setup to resolve `.css` files, you can place that in the `<script>` section of a SFC. You could also place it in the `<style>` section with this syntax when using sass/scss:

```css
@import '~vue-transmit/dist/vue-transmit.css'
```

**Comment by alexsasharegan** [comment]
If you're not seeing a dropzone on your page, you might need to add content to the default slot.

```html
<vue-transmit>
  <div class="d-flex align-items-center justify-content-center w-100"
       style="height:50vh; border-radius: 1rem;">
    <button class="btn btn-primary"
            @click="triggerBrowse">Upload Files</button>
  </div>
</vue-transmit>
```

The default slot should contain your markup for getting an upload started. This could be a file uploade button and/or dropzone-like styling.

**Comment by benirose** [comment]
I wasn't sure if vue-loader would do for me in terms of loading CSS files. I had tried putting it in `style` tag but was missing the tilde, thanks!

P.S. It took me a bit of digging to realize the styles for this were in a separate file. Can I recommend putting that somewhere on the docs?

**Comment by benirose** [comment]
Oh, I didn't realize the default slot was empty. I can see that's kind of in the docs as well, but might be worth calling out as well. Maybe I'm just a dummy tho.

**Comment by alexsasharegan** [comment]
Yes, it's definitely a faux pas of mine! If you want to PR that, go right ahead! Otherwise we can rename this issue to something like `fix(docs): missing css import info` and leave it open till I get to it.

**Comment by alexsasharegan** [comment]
I'm definitely up for some better explanation in the docs! It's always hard to introduce the concept to this since I've been working with it for so long. I do want to give this lib a dedicated doc site with vuepress with v9 once I finish the firebase driver.

**Comment by alexsasharegan** [comment]
Oh wow! That's pretty cool. Did you use vue-cli? I just know the tilde seems to be a common alias in css to resolve from node_modules.

**Comment by benirose** [comment]
No, this is a hand rolled webpack config on a legacy Symfony 1.4 project! We're doing some unconventional things, so it can be hard to figure out what the right config is between webpack/vue/babel/etc! 

I'm adding an FAQ to the bottom about styling/default slot for anyone who runs into a similar issue of not seeing the component the first time they try to use it. PR will be incoming shortly!
