### ISSUE TITLE
File errorMessage never set

### ISSUE THREAD

**Issue by Odaeus** [alexsasharegan/vue-transmit#47]
On VTransmitFile there's an `errorMessage` property but it looks like this is initialised to an empty string and then never used again if I've read the code correctly?

It seems like it should be set in the [`errorProcessing`](https://github.com/alexsasharegan/vue-transmit/blob/master/src/components/VueTransmit.vue#L848) method but currently isn't.

I know we can handle errors by catching the error event but it seems quite useful to have the error message stored with the file when it has the `Error` state.

**Comment by alexsasharegan** [comment]
This a great catch! I agree it should get written to the file in the errorProcessing. The two spots for errors are the accept phase and the upload. I'll write those up to write properly!

**Comment by alexsasharegan** [comment]
By the way, on my production app that uses this library (v8.x), the error messages are written to the file object. I'm trying to trace where that's happening, but not seeing it in my app, or in the library right now. I'd like to find how the current mechanism is working in my app so I don't miss something implementing this.

**Comment by Odaeus** [comment]
Thanks!

**Comment by alexsasharegan** [comment]
Thanks for catching this! I'm changing up jobs, so I should have some time to spend finalizing and releasing v9 this coming week.
