### ISSUE TITLE
Max Files not being respected

### ISSUE THREAD

**Issue by benirose** [alexsasharegan/vue-transmit#49]
I've set `:maxFiles=1`, which prevents selecting multiple files in the uploader, but when I click the uploader and select a different file, I end up with two files in the `files` array, and the first one is still there. I tried to dig in to the code to see what's going on, and it looks like some of the logic around `maxFiles` is being applied to the `<input type="file">` but not to the rest of the component. How can I prevent users from trying to queue more than one file?

**Comment by alexsasharegan** [comment]
Let me ensure I understand. You want to only upload 1 file at a time, but not limit the overall number of files uploaded? And what do you want in terms of being able to drop/select multiple vs. single file?

**Comment by benirose** [comment]
Sorry, no. I want to basically use it as a single file upload. Only one can be queued (and then I do some checks) and then they hit the upload button and it sends off. If they fail the checks, I want them to be able to replace the file that's in the queue.

**Comment by alexsasharegan** [comment]
So with the current implementation, I would expect that setting `maxFiles: 1` will limit one file at a time, but it will not limit to one file if the first file fails. The logic is to limit to `maxFiles` of accepted files.

You are wanting to limit to 1 file always? Why not remove the previous file on `'added-file'`?

**Comment by benirose** [comment]
I can try removing previous file on file added. I think the confusion comes around the different stages, with added files, accepted files, queued files, and uploaded files being different places that `maxFiles` could apply to. I would imagine that if I had one file in the queue, I wouldn't be able to add another if `maxFiles` was 1.

**Comment by alexsasharegan** [comment]
Yeah, it's definitely confusing. This comes from the perspective that the constraint for max files really applies to where the resource is going--i.e. your backend.

**Comment by alexsasharegan** [comment]
Is this issue resolved? Is it just a matter of understanding what maxFiles controls that is ultimately the issue to be clarified? If there's nothing further, I'll probably close this in the next day or so.
