### ISSUE TITLE
Problem with data update on thumbnails

### ISSUE THREAD

**Issue by johnkingsley** [alexsasharegan/vue-transmit#50]
Hi Alex,

First off, thanks for your Vue component.  It's very useful!

What I'm seeing is that the thumbnail doesn't show on the window properly. However I'm not sure if this is a bug or not.

This can be reproduced by modifying `test/public/index.html` as follows:
```
                    cols="4">
                <b-card :title="file.name"
                        :sub-title="file.type"
-                       :img-src="file.meta.url"
+                       :img-src="file.dataUrl"
                        :img-alt="file.name"
                        img-top>
-                  <pre>{{ file | json }}</pre>
+              <!--     <pre>{{ file | json }}</pre>    -->
                </b-card>
             </b-col>
          </b-row>
```
When you add a file using the modified test, the thumbnail isn't immediately loaded.

I have found two fixes, but I'm not sure how to proceed. Any advice would be appreciated.

### Fix 1
Allow Vue to see the `_dataUrl` property in `src/classes/VTransmitFile.ts` by making it enumerable, like this:
```
        set dataUrl(value) {
               this._dataUrl = value;
        }
```
Once Vue can see this data is modified, then it can update the window as expected, just like all the other properties on VTransmitFile.

This obviously isn't ideal, since the comment says:
> // Use non-enumerable data url to avoid copying around large data sets

### Fix 2
If this change is added to the test, it works as expected:
```
                              @success="onUploadSuccess"
                              @success-multiple="onUploadSuccessMultiple"
                              @timeout="onError"
+                             @thumbnail="$forceUpdate()"
                              @error="onError">
                   <flex-col align-v="center"
                             class="h-100">
```
Here the onus is on the user to update the display when the thumbnail is loaded.

Thanks in advance!
John

**Comment by alexsasharegan** [comment]
This is an interesting edge case! At first glance, I think maybe a boolean prop on the file class, `thumbnailLoaded`, could solve this. We can let vue observe this prop, but we can still avoid the issues around enumerable data urls (they've blown up localStorage on me before).

**Comment by johnkingsley** [comment]
OK, let me try that and see if it works.
If it does, I'll send you a pull request.
Thanks!

**Comment by alexsasharegan** [comment]
Heck yes!

**Comment by johnkingsley** [comment]
It worked!

At first it didn't but then I realized I needed to read `thumbnailLoaded`
in `get dataUrl()` otherwise Vue wouldn't pick up the change.
Below is the diff.

Shall I make a pull request?

```
diff --git a/src/classes/VTransmitFile.ts b/src/classes/VTransmitFile.ts
index d672860..41d46c0 100644
--- a/src/classes/VTransmitFile.ts
+++ b/src/classes/VTransmitFile.ts
@@ -35,6 +35,8 @@ export class VTransmitFile {
        public width: number = 0;
        public height: number = 0;
        public errorMessage: string = "";
+       public thumbnailLoaded: boolean = false;
+
        /**
         * `adapterData` is data meant for use by an upload adapter only.
         */
@@ -104,7 +106,7 @@ export class VTransmitFile {
        }
 
        get dataUrl() {
-               return this._dataUrl || "";
+               return this.thumbnailLoaded ? this._dataUrl : "";
        }
 
        set dataUrl(value) {
@@ -115,6 +117,7 @@ export class VTransmitFile {
                        configurable: true,
                        writable: true,
                });
+               this.thumbnailLoaded = true;
        }
 
        static idFactory() {

```

**Comment by alexsasharegan** [comment]
Smart man! You know how this gig works! I was just thinking about that too. That looks pretty solid to me. Are you going to PR the main branch, or the 8.x? If I could share a beer, both would definitely earn that 🍺

**Comment by johnkingsley** [comment]
I think I owe you a case of beer for making this component. :-)
I will make 2 PRs.

**Comment by alexsasharegan** [comment]
Just curious, what version are you working with in your app?

**Comment by johnkingsley** [comment]
I was using 8.1.2 then switched to master/HEAD when I hit these problems (this problem and my other PR). Now that we've figured them out, I'll probably go back to 8.1.2 and work around them for now (should be easy).

It's probably not a good idea to use alpha code in production app.  :-)

**Comment by alexsasharegan** [comment]
Yeah, it's hard because the next version offers some big size improvements. But I've been really trying to get the upload driver api boundary worked out.

**Comment by alexsasharegan** [comment]
Thanks for the fix! New version up on npm for `v8.x`. Go ahead and be the guinea pig!

**Comment by cookmscott** [comment]
Hey all... I'm working with `9.0.0` and I'm running into the same issue John had originally posted. His `thumbnailLoaded` change doesn't look like they made it into the latest release. Is there a reason for that? I've been using his "Fix 2" as an intermediate solution.
