### ISSUE TITLE
Direct url to a vue route display blank on production

### ISSUE THREAD

**Issue by Tahywoh** [alexsasharegan/vue-transmit#55]
In development mode, if i visit the specific url directly, it work perfectly, but in production, it display blank.
However, if i remove mode of history, it worked perfectly both in development and production.
But, i do not want to do without mode of history, how do i resolve that?

**Comment by alexsasharegan** [comment]
This sounds entirely off-topic. Please start by visiting the official vue forums for generic questions. This is for vue-transmit issues only.

Vue forums: https://forum.vuejs.org/c/general

**Comment by Tahywoh** [comment]
ok, thanks
