### ISSUE TITLE
Overriding default headers on requests

### ISSUE THREAD

**Issue by rrgahan** [alexsasharegan/vue-transmit#56]
The default headers for a request include `Cache-Control`, but the server I'm POSTing to does not allow that header. I have tried to override this by adding a `headers`  value in my options, but it still sends `Cache-Control`. Is there a way to remove this header?

**Comment by alexsasharegan** [comment]
Which version are you running?

**Comment by rrgahan** [comment]
8.1.4

**Comment by alexsasharegan** [comment]
The default headers are merged with user-defined headers via Object.assign, and then checked for truthiness, so you could do this:

```js
const headersToPassToVTransmit = {
  'Cache-Control': false
};
```

**Comment by rrgahan** [comment]
Ah setting it to false worked. 

```
options: {
  acceptedFileTypes: [],
  url: videoUpload,
  headers: {
    'Cache-Control': false,
    'X-Requested-With': false
    }
},
```

Thanks!
