### ISSUE TITLE
vue-transmit messes up vue devtools?

### ISSUE THREAD

**Issue by eminos** [alexsasharegan/vue-transmit#6]
It seems that as soon as I import vue-transmit, vue devtools for chrome stops showing events from the root component and other components, only shows events emitted by vue-transmit.

An other related strange thing is that when selecting a vue-transmit instance in the tree in vue devtools, it shows the data from the Root component or some direct child component of that.

I'm using Laravel Mix (webpack). Latest versions.
No errors, just weirdness in vue devtools.

This might be a vue devtools bug, I guess, but I still wanted to let you know. It starts happening as soon as I import vue-transmit:
`import VueTransmit from "vue-transmit";`

**Comment by alexsasharegan** [comment]
Those are some odd behaviors you're experiencing. I haven't seen any of those on my own builds, but I'm working with webpack sans Laravel Mix. Any extra info you can pass along? Perhaps the underlying webpack config, vue devtools version, browser version, etc.

**Comment by eminos** [comment]
Yes. It's all latest versions. Latest stable Chrome on Windows. Latest Laravel Mix with its default webpack config. I'm using HMR in development, which I suspected could be causing problems, but I had the same issues without it.

For now, I had to switch to elements-ui upload component. But I like vue-transmits customizability better.

**Comment by alexsasharegan** [comment]
Personally I don't think a devtool feature would be sufficient reason to avoid production usage, but I respect that decision all the same. Element-ui is an excellent choice 👍 

I'm going to close this issue since it appears an upstream problem, via your comment: https://github.com/vuejs/vue-devtools/issues/380#issuecomment-341294114

Please update with any new info!
