### ISSUE TITLE
CSS conflict with Bootsrap

### ISSUE THREAD

**Issue by ligne13** [alexsasharegan/vue-transmit#60]
Hi,

there is a CSS conflict with Bootrap class names. Vue-transmit injects in the <head> a <style> tag declaring a class named `.progress`which is also declared and used by Bootstrap in its Progress bar component. The main problem is that your `.progress` class set `opacity: 0` so Bootstrap progress bars are not visible.
Can you namespace your CSS class names to avoid these conflicts ?

thanks

**Comment by alexsasharegan** [comment]
This is inaccurate. Have a look at the css here: https://github.com/alexsasharegan/vue-transmit/blob/8.x/src/components/VueTransmit.vue#L32-L62

Conflicting CSS must be coming from another source.
