### ISSUE TITLE
Typescript definition exports missing?

### ISSUE THREAD

**Issue by phil-scott-78** [alexsasharegan/vue-transmit#61]
I might be taking crazy pills but it seems the typescript definition is missing some items. 

With version 8.1.4 `index.d.ts` simply contains this

``` typescript
declare const _default: {
    install(Vue: any, _options: any): void;
    name: string;
};
export default _default;
```

This breaks the ability to do with an error that `VueTransmit` isn't exported

``` typescript 
import { VueTransmit } from 'vue-transmit';

@Component({
  components: { VueTransmit },
})
```

Doing a `import VueTransmit from 'vue-transmit'` and calling `vue.use` still works because the definition does export a default member, but it's the plugin object not the component.

**Comment by phil-scott-78** [comment]
All good. Plugin worked fine, just wanted to give you a heads up if that was something you missed. Thanks for the quick reply!

**Comment by alexsasharegan** [comment]
Ah, okay! Glad it's working! Always been frustrated by the issues with types in SFC's. Maybe once I have time to work back on v9 I can just write it in a `.ts` file with a render function so it types properly.
