### ISSUE TITLE
Axios transport adapter?

### ISSUE THREAD

**Issue by irazasyed** [alexsasharegan/vue-transmit#62]
It would be great if this package ships with an [axios](https://github.com/axios/axios) transport implementation as well. Possible?

It's widely used among Laravel developers with vuejs as their front-end.

**Comment by alexsasharegan** [comment]
That would make this library depend on axios. It uses the native XMLHttpRequest, the same mechanics Axios uses under the hood. What benefit would adding axios bring?

**Comment by irazasyed** [comment]
I don't think it'll make it dependent. It's an additional adapter which one can swap with the default. However, I was evaluating the perks right now and it seems the native is just fine for now. Thought we could make use of promises, fluent API, etc. but then there isn't much use-case for this library as such.

Anyway, Thanks for the prompt response and for the library! Just started implementing and testing it. Works good so far 👍

**Comment by alexsasharegan** [comment]
Glad to hear it! Once I get time spend on v9, it'll open more possibilities for swapping things out at the transport layer. It's actually architected using the adapter pattern so I can support things like firebase with a 'driver' module. If you poke around the master branch, you probably see the plug & play driver setup.

**Comment by irazasyed** [comment]
Sounds good. Looking forward to it!

I'll explore in the meantime :)
