### ISSUE TITLE
Send additional parameter when uploading file to server

### ISSUE THREAD

**Issue by sumit4bansal** [alexsasharegan/vue-transmit#63]
I need to send additional parameter to sever when file is being uploaded like what type of file it is and some other parameters.

How this can be achieved?

**Comment by sourenaraya** [comment]
adapterOptions.params. Its in documentation.

**Comment by alexsasharegan** [comment]
@sourenaraya is correct. If you're running v8, you can view the props here: https://github.com/alexsasharegan/vue-transmit/tree/8.x#props-vue-transmit

You'll v8 uses `params`. It's likely you're using v8, since it's the default install from npm.
