### ISSUE TITLE
WebSocket transport example

### ISSUE THREAD

**Issue by AMontagu** [alexsasharegan/vue-transmit#70]
Hello !

I come to this project because of this line in the README:
```
Vue-Transmit also has a modular upload transport. The default transport implementation uses XMLHttpRequest to upload client-side files using multi-part form data, but this could be swapped for a custom implementation for something like Firebase or WebSockets
```

I need to use both HTTP and WebSocket protocol to upload some files. 

Unfortunately I wasn't able to find how to override the default transport implementation in the docs. 

I suppose its some options to put [here](https://github.com/alexsasharegan/vue-transmit#adapter-options-xhruploadadapter) but can't find which ones.

I go until find this:
https://github.com/alexsasharegan/vue-transmit/pull/27

But if you have an existing example of WebSocket transport example it will save me a lot of time.

Thanks you.

**Comment by alexsasharegan** [comment]
The first thing to keep in mind here is that this is only available in the v9 alpha release or the master branch. It's not finalized yet, and I now work in React for my day job, so I've yet to get time to flesh this out into it's simplest form.

So the way you can inject a custom adapter is through the prop `uploadAdapter` ([view source from release tag v9.0.0-alpha.11](https://github.com/alexsasharegan/vue-transmit/blob/v9.0.0-alpha.11/src/components/VueTransmit.vue#L274-L277)). 

You'll write a class that implements the 2 methods of the uploader interface found [here](https://github.com/alexsasharegan/vue-transmit/blob/v9.0.0-alpha.11/src/core/interfaces.ts). If you don't know TypeScript, here's the idea:

You're class constructor receives a context object (`arguments[0]`) and the options object passed to vue-transmit's prop `adapterOptions` (`arguments[1]` [view option source](https://github.com/alexsasharegan/vue-transmit/blob/v9.0.0-alpha.11/src/components/VueTransmit.vue#L270-L273)). The options are whatever special things you need, but the context object has what you need to communicate with the vue-transmit component. You can take a look at the context object class [here](https://github.com/alexsasharegan/vue-transmit/blob/v9.0.0-alpha.11/src/classes/VTransmitUploadContext.ts).

The two methods you need to support are `uploadFiles` and `cancelUpload`. It's ideal that you implement progress events through the context object, but that's up to you if you need it or not. The key is to take the array of `VTransmitFile` (which have the native file object inside), kick off your upload, and return a promise that resolves with a success or failure object looking like this:

```js
const successPayload = {
  ok: true,
  data: {
    // anything you want
  },
};

const failurePayload = {
  ok: false,
  err: {
    type: 0, // or 1 for timeout
    message: "", // must be a string
    data: {
      // anything you want
    },
  },
};
```

Here's some pseudo code of a websocket adapter class:

```js
const UploadErrors = {
  Any: 0,
  Timeout: 1,
};

class WSUploadAdapter {
  constructor(context, options) {
    this.context = context;
    // ...use your options if needed
    // This might be how you implement cancellation
    this.uploadsInProgress = new Map();
  }

  uploadFiles(files) {
    // maybe add a cancel method by their id
    files.map(file => {
      this.uploadsInProgress.set(file.id, () => {
        this.cancel(file);
      });
    });

    return this.doWebSocketUpload(files)
      .then(result => {
        // remove them on success
        files.map(file => {
          this.uploadsInProgress.delete(file.id);
        });

        return {
          ok: true,
          data: result,
        };
      })
      .catch(err => {
        // remove them on failure
        files.map(file => {
          this.uploadsInProgress.delete(file.id);
        });

        return {
          ok: false,
          err: {
            // If you know it's a timeout, pass the 1
            // Timeouts are the only special error case
            type: UploadErrors.Any,
            // wherever you get this, just make it a string
            message: err.message,
            // anything you want here, I believe it's emitted in the error event
            data: err,
          },
        };
      });
  }

  cancelUpload(file) {
    let cancel = this.uploadsInProgress.get(file.id);
    if (cancel) {
      cancel();
    }
  }

  doWebSocketUpload(files) {
    // ...
  }

  cancel(file) {}
}
```

**Comment by AMontagu** [comment]
Thank you for you fast answer. I wiil begin by code my WS transport layer and come back here if I decide to implement it with your librairie. Even PR it if I found the code clean and if do not use third party librairie for the WS file transfer.
